### Install httpd and launch a web server in EC2
### Uses Default VPC and Subnets

Resources:
  # EC2 Creation
  cfnDemoEc2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0440d3b780d96b29d
      InstanceType : t2.micro
      Tags:
        - Key: name
          Value: cfnDemoEc2
      SecurityGroups:
        - !Ref cfnDemoSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>CFN Demo</h1>" > /var/www/html/index.html

  cfnDemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: cfnDemoSecurityGroup
      SecurityGroupIngress:
        - CidrIp : 0.0.0.0/0
          FromPort : 22
          ToPort : 22
          IpProtocol : tcp
        - CidrIp : 0.0.0.0/0
          FromPort : 80
          ToPort : 80
          IpProtocol : tcp
      Tags:
        - Key: name
          Value: cfnDemoSecurityGroup